### ISSUE TITLE
Twitter files causing build issue

### ISSUE THREAD

**Issue by engn33r** [ralscha/spring4ws-demos#1]
I encountered a maven build issue after cloning this repo and building from the top level directory. The error I encountered was:
```
2021-03-30 ERROR 54269 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'twitterHandler': Invocation of init method failed; nested exception is java.lang.NullPointerException
```
I resolved this removing the directory at /src/main/java/ch/rasc/s4ws/twitter. A recent commit, 03eb0f4, removed some twitter code but not everything. Is there a better solution, or should this directory be deleted?

**Comment by ralscha** [comment]
To run the Twitter demo you need to specify the Twitter keys. Although I'm not sure if that still works, because I no longer have a Twitter account. 

src/main/resources/application-development.properties
```
twitter4j.oauth.consumerKey=
twitter4j.oauth.consumerSecret=
twitter4j.oauth.accessToken=
twitter4j.oauth.accessTokenSecret=
```

You could simply delete the directory: `src/main/java/ch/rasc/s4ws/twitter`

**Comment by engn33r** [comment]
Thank you, this makes sense. I did not notice that there were credentials that needed to be entered before I tried to build the examples. Removing the directory works well enough for now.
